name: Docker Publish

on:
  push:
    branches:
      - main
      - master

env:
  IMAGE_NAME: "buyfakett/rsyslog"
  IMAGE_TAG: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2           

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
            images: ${{ env.IMAGE_NAME }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}